package deviate.capstone.ipss.auth.service;

import java.util.Objects;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import deviate.capstone.ipss.auth.Dto.Requests.LoginRequest;
import deviate.capstone.ipss.auth.Dto.Responses.LoginResponse;
import deviate.capstone.ipss.auth.entity.User;
import deviate.capstone.ipss.auth.repository.UserRepository;
import deviate.capstone.ipss.shared.UnauthorizedException;

@Service
public class AuthService {
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtService jwtService;

    public AuthService(UserRepository userRepository, PasswordEncoder passwordEncoder, JwtService jwtService) {
        this.userRepository = Objects.requireNonNull(userRepository);
        this.passwordEncoder = Objects.requireNonNull(passwordEncoder);
        this.jwtService = Objects.requireNonNull(jwtService);
    }

    /**
     * This Java function validates a login attempt by fetching a user from the database based on the provided government email, checking the password, and account status before generating a JWT token.
     * 
     * @param request The `validateLoginAttempt` method takes a `LoginRequest` object as a parameter. The `LoginRequest` object likely contains the user's government email and password needed for authentication.
     * @return The method is returning a JWT token generated by the `jwtService` for the authenticated user.
     */
    public LoginResponse validateLoginAttempt(LoginRequest request) {
        String govtEmail = request.govtEmail();
        String password = request.password();

        // 1. Fetches user with exact email from the database
        User user = userRepository.findByGovtEmail(govtEmail)
            .orElseThrow(() -> new UnauthorizedException("Invalid credentials"));

        //2. If password is not the same, attempt is stopped immediately
        if (!passwordEncoder.matches(password, user.getPassword())) {
            throw new UnauthorizedException("Password is incorrect");
        }

        // 3. Check account status
        if (!user.isActive()) {
            throw new UnauthorizedException("Invalid credentials");
        }

        String token = jwtService.generateToken(user);

        return new LoginResponse(
            token,
            "Bearer",
            user.getId(),
            user.getRole().name()
        );
    }

}
