package deviate.capstone.ipss.auth.service;

import java.util.Objects;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

@Service
public class PasswordService {

    private final PasswordEncoder passwordEncoder;

    public PasswordService(PasswordEncoder passwordEncoder) {
        this.passwordEncoder = Objects.requireNonNull(passwordEncoder);
    }
    
    /**
     * The function creates a temporary password by combining the last name and government ID, then encoding it using a password encoder.
     * 
     * @param lastName The `lastName` parameter is a String that represents the last name of a person.
     * @param govtId The `govtId` parameter typically refers to a government-issued identification number, such as a social security number, driver's license number, or passport number.
     * @return The method `createTemporaryPassword` returns a hashed password generated by encoding the concatenation of the `lastName` and `govtId` parameters using a `passwordEncoder`.
     */
    public String createTemporaryPassword(String lastName, String govtId) {
        String rawPassword = String.join(".", lastName, govtId);
        String hashedPassword = passwordEncoder.encode(rawPassword);

        return hashedPassword;
    }
}
